### ISSUE TITLE
vs_clockwork load crash.

### ISSUE THREAD

**Issue by REFIRSER2** [ValkyrienSkies/Create-Interactive-Issues#103]
vs version 2.0.3 beta-6
clockwork version 0.1.16

-- MOD vs_clockwork --
Details:
	Mod File: /C:/Users/User/curseforge/minecraft/Instances/minecraft 1.20.1 terrapack/mods/clockwork-1.20.1-0.1.16-forge-b3b22e39fe.jar
	Failure message: Clockwork: Create x Valkyrien Skies (vs_clockwork) has failed to load correctly
		java.lang.NoSuchMethodError: 'org.valkyrienskies.core.impl.networking.RegisteredHandler org.valkyrienskies.core.impl.hooks.VSEvents$ShipLoadEvent$Companion.on(java.util.function.Consumer)'
	Mod Version: 1.20.1-0.1.16-forge-b3b22e39fe
	Mod Issue URL: https://github.com/ValkyrienSkies/Clockwork-Issues/issues
	Exception message: java.lang.NoSuchMethodError: 'org.valkyrienskies.core.impl.networking.RegisteredHandler org.valkyrienskies.core.impl.hooks.VSEvents$ShipLoadEvent$Companion.on(java.util.function.Consumer)'
Stacktrace:
	at org.valkyrienskies.clockwork.ClockworkMod.init(ClockworkMod.java:36) ~[clockwork-1.20.1-0.1.16-forge-b3b22e39fe.jar%23187!/:?] {re:classloading}
	at org.valkyrienskies.clockwork.forge.ClockworkModForge.<init>(ClockworkModForge.java:55) ~[clockwork-1.20.1-0.1.16-forge-b3b22e39fe.jar%23187!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23214!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23213!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by blockninja124** [comment]
This is **only** for create interactive issues. This is a clockwork crash. It will probably be fixed next clockwork update.
