### ISSUE TITLE
Unable to Configure on Fabric

### ISSUE THREAD

**Issue by dhouck** [ValkyrienSkies/Create-Interactive-Issues#66]
I believe Iʼve seen references to configuration options, but I cannot find any sort of config screen or config file.

When I try to configure via Mod Menu, I get an icon saying configuration canʼt happen, a tooltip saying that Create Interactive through a NPE, and this in the logs:
```
[17:58:36] [Render thread/ERROR]: Error from mod 'create_interactive'
java.lang.NullPointerException: There cannot be no categories or fallback category!
	at me.shedaniel.clothconfig2.impl.ConfigBuilderImpl.build(ConfigBuilderImpl.java:231) ~[cloth-config-11.1.106-d0ed94b1a5f0a197.jar:?]
	at org.valkyrienskies.mod.compat.clothconfig.VSClothConfig.createConfigScreenFor(VSClothConfig.java:42) ~[valkyrienskies-120-2.1.3-beta.1.jar:?]
	at org.valkyrienskies.create_interactive.aux.ḝᾀ.this(Unknown Source) ~[create_interactive-1201-fabric-1.0.2-beta.1.jar:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:61) ~[modmenu-7.2.2.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:114) ~[modmenu-7.2.2.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:15) ~[modmenu-7.2.2.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:299) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

**Comment by dhouck** [comment]
(Note that if I misunderstood something and there should be no config options then it should be possible to make ModMenu not show a config button at all, instead of one showing the config screen is broken)

**Comment by Billnotic** [comment]
In the VS2 discord people have mentioned a config for this mod, I am on Forge and no config is being generated for me either.

**Comment by blockninja124** [comment]
Fixed in 1.1.1 since config got re-written
